version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  deploy:
    docker:
      - image: cimg/node:16.15.0
    environment:
     AWS_REGION: eu-west-2
    steps:
      - checkout
      - aws-s3/sync:
          from: . # From where???
          to: 's3://www.sean-gordon.com/'
workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main